### ISSUE TITLE
Fallback to SystemEnvironment

### ISSUE THREAD

**Issue by camilohollanda** [gordalina/hush#5]
Hey @gordalina,
Very nice job, thanks for your contribution!

I would like to keep the config of the app the most centralized as possible. For example, I would like to fall back the database configuration in the test environment to an ENV var.

What do you think about providing a fallback to SystemEnvironment provider?

**Comment by gordalina** [comment]
> I would like to keep the config of the app the most centralized as possible. For example, I would like to fall back the database configuration in the test environment to an ENV var.

The elixir way is to have that configuration in `config/test.exs`

> What do you think about providing a fallback to SystemEnvironment provider?

If there's a good argument for the use-case, anything can be implemented. I don't think that adding a fallback because you don't want to have it configured in the test environment warrants a change in hush.

Feel free to re-open at any time if you feel this should be addressed.
